name: Node.js CI/CD for AWS EC2

on:
  push:
    branches: [ stag ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6        

      - name: Setup Node.js Environment
        uses: actions/setup-node@v6      
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Code Build
        run: npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6       

      - name: Execute Remote SSH Commands & Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            mkdir -p ~/sample-workflows
            cd ~/sample-workflows

            if [ ! -d ".git" ]; then
              git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .
            else
              git pull origin stag
            fi

            echo "Installing dependencies..."
            npm ci --omit=dev

            echo "Starting/Reloading application with PM2..."
            pm2 describe sample-app > /dev/null 2>&1
            if [ $? -eq 0 ]; then
              echo "App is running. Reloading..."
              pm2 reload sample-app --update-env
            else
              echo "App is not running. Starting..."
              pm2 start app.js --name "sample-app"
            fi

            pm2 save